apiVersion: v1
kind: Namespace
metadata:
  name: bbbb
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: bbbb
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: bbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.10
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /data/nvme/zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: bbbb
spec:
  ports:
    - name: external
      port: 9092
      targetPort: 9092
    - name: internal
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: bbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.10
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://192.168.56.103:9092,PLAINTEXT_INTERNAL://kafka:9093
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT_INTERNAL
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          hostPath:
            path: /data/nvme/kafka
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: bbbb
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: schema-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: bbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.4.10
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka:9093
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb
  namespace: bbbb
spec:
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: ksqldb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
  namespace: bbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
        - name: ksqldb
          image: confluentinc/cp-ksqldb-server:7.4.10
          ports:
            - containerPort: 8088
          env:
            - name: KSQL_CONFIG_DIR
              value: /etc/ksqldb
            - name: KSQL_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka:9093
            - name: KSQL_LISTENERS
              value: http://0.0.0.0:8088
            - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: KSQL_KSQL_SERVICE_ID
              value: ksqldb_service
            - name: KSQL_KSQL_HIDDEN_TOPICS
              value: '^_.*'
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: bbbb
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: kafka-connect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: bbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:7.4.10
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: kafka:9093
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: kafka-connect
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: connect-cluster
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: _connect-configs
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: _connect-offsets
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: _connect-status
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
---
apiVersion: v1
kind: Service
metadata:
  name: akhq
  namespace: bbbb
spec:
  ports:
    - port: 9080
      targetPort: 8080
  selector:
    app: akhq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: bbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq:0.26.0
          ports:
            - containerPort: 8080
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    kafka-single:
                      properties:
                        bootstrap.servers: "kafka:9093"
                      schema-registry:
                        url: "http://schema-registry:8081"
                      connect:
                        - name: "kafka-connect"
                          url: "http://kafka-connect:8083"
                      ksqldb:
                        - name: "ksqldb-local"
                          url: "http://ksqldb:8088"
